# Generated by Django 4.2.26 on 2025-11-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField(help_text='Timestamp Unix del momento de la consulta (epoch time)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro en la base de datos')),
                ('total_states', models.IntegerField(default=0, help_text='Número total de estados de vuelos en este snapshot')),
            ],
            options={
                'db_table': 'flight_snapshots',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='FlightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(db_index=True, help_text='Código ICAO24 único del transponder (índice 0)', max_length=6)),
                ('callsign', models.CharField(blank=True, db_index=True, help_text='Indicativo de llamada del vuelo (índice 1)', max_length=8, null=True)),
                ('origin_country', models.CharField(db_index=True, help_text='País de origen del vuelo (índice 2)', max_length=100)),
                ('time_position', models.BigIntegerField(blank=True, help_text='Timestamp Unix de la última posición (índice 3)', null=True)),
                ('last_contact', models.BigIntegerField(help_text='Timestamp Unix del último contacto (índice 4)')),
                ('longitude', models.FloatField(blank=True, help_text='Longitud en grados decimales (índice 5)', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitud en grados decimales (índice 6)', null=True)),
                ('baro_altitude', models.FloatField(blank=True, help_text='Altitud barométrica en metros (índice 7)', null=True)),
                ('on_ground', models.BooleanField(default=False, help_text='Si está en tierra (índice 8)')),
                ('velocity', models.FloatField(blank=True, help_text='Velocidad en m/s (índice 9)', null=True)),
                ('true_track', models.FloatField(blank=True, help_text='Rumbo verdadero en grados 0-360° (índice 10)', null=True)),
                ('vertical_rate', models.FloatField(blank=True, help_text='Velocidad vertical en m/s (índice 11)', null=True)),
                ('sensors', models.JSONField(blank=True, help_text='Array de IDs de sensores (índice 12)', null=True)),
                ('geo_altitude', models.FloatField(blank=True, help_text='Altitud geométrica en metros (índice 13)', null=True)),
                ('squawk', models.CharField(blank=True, help_text='Código transponder squawk (índice 14)', max_length=4, null=True)),
                ('spi', models.BooleanField(default=False, help_text='Si SPI está activo (índice 15)')),
                ('position_source', models.IntegerField(blank=True, help_text='Fuente de posición: 0=ADS-B, 1=ASTERIX, 2=MLAT (índice 16)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('snapshot', models.ForeignKey(help_text='Snapshot al que pertenece este estado de vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='API.flightsnapshot')),
            ],
            options={
                'db_table': 'flight_states',
                'ordering': ['-last_contact', 'icao24'],
            },
        ),
        migrations.AddIndex(
            model_name='flightsnapshot',
            index=models.Index(fields=['-time'], name='flight_snap_time_b3412c_idx'),
        ),
        migrations.AddIndex(
            model_name='flightsnapshot',
            index=models.Index(fields=['-created_at'], name='flight_snap_created_2cdf75_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['snapshot', 'icao24'], name='flight_stat_snapsho_cae750_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['snapshot', '-last_contact'], name='flight_stat_snapsho_ea7da0_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['callsign'], name='flight_stat_callsig_af262a_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['origin_country'], name='flight_stat_origin__71670a_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['on_ground'], name='flight_stat_on_grou_643a33_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['-last_contact'], name='flight_stat_last_co_c9f146_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstate',
            index=models.Index(fields=['icao24'], name='flight_stat_icao24_00d57d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightstate',
            unique_together={('snapshot', 'icao24', 'last_contact')},
        ),
    ]
